version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
         command: sudo chmod +x ./gradlew
      - run:
      	 name: Downloading gradle
      	 command: wget https://services.gradle.org/distributions/gradle-5.0-bin.zip -P /tmp
      - run:
      	 name: extracting gradle
      	 command: sudo unzip -d /opt/gradle /tmp/gradle-*.zip
      - run:
      	 name: exporting vars
      	 command: export GRADLE_HOME=/opt/gradle/gradle-5.0 && export PATH=${GRADLE_HOME}/bin:${PATH} && sudo chmod +x /etc/profile.d/gradle.sh && source /etc/profile.d/gradle.sh
      - run:
          name: generating wrapper
          command: gradle wrapper
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/ 
          path: app/build/reports
          destination: reports
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: app/build/test-results
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples

